# Generated by Django 4.2.7 on 2026-03-27 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="打卡备注")),
                (
                    "check_in_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="打卡日期",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, default="未获取位置", max_length=200, verbose_name="位置名称"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        default=0,
                        max_digits=10,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        default=0,
                        max_digits=10,
                        verbose_name="经度",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, default=9999, null=True, verbose_name="精度(米)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("revoked", "已撤销"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "points_earned",
                    models.PositiveIntegerField(default=0, verbose_name="获得积分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="打卡时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "打卡记录",
                "verbose_name_plural": "打卡记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckInPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="checkins/%Y/%m/%d/", verbose_name="照片"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "verbose_name": "打卡照片",
                "verbose_name_plural": "打卡照片",
            },
        ),
        migrations.CreateModel(
            name="PointRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(help_text="正数为增加，负数为减少", verbose_name="积分变化"),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="如：每日打卡、连续打卡奖励等", max_length=100, verbose_name="获得原因"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "related_checkin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="checkins.checkin",
                        verbose_name="关联打卡记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分记录",
                "verbose_name_plural": "积分记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
