# Generated by Django 4.2.7 on 2026-03-27 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checkins", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="checkinphoto",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="checkins.checkin",
                verbose_name="所属打卡",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="activities.activity",
                verbose_name="所属活动",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="registration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkin",
                to="activities.activityregistration",
                verbose_name="关联报名记录",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_checkins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="打卡用户",
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["user", "created_at"], name="checkins_ch_user_id_b71430_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["activity", "status"], name="checkins_ch_activit_9ee08f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checkin",
            unique_together={("user", "activity", "check_in_date")},
        ),
    ]
