# Generated by Django 4.2.7 on 2026-03-19 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0006_activity_closed_at_activity_closed_by_and_more"),
        ("checkins", "0003_pointrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointrecord",
            name="related_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="checkins.checkin",
                verbose_name="关联打卡记录",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="activities.activity",
                verbose_name="所属活动",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="registration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkin",
                to="activities.activityregistration",
                verbose_name="关联报名记录",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_checkins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="打卡用户",
            ),
        ),
        migrations.AlterField(
            model_name="checkinphoto",
            name="checkin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="checkins.checkin",
                verbose_name="所属打卡",
            ),
        ),
        migrations.AlterField(
            model_name="pointrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
        ),
        migrations.AlterField(
            model_name="pointrecord",
            name="points",
            field=models.IntegerField(help_text="正数为增加，负数为减少", verbose_name="积分变化"),
        ),
        migrations.AlterField(
            model_name="pointrecord",
            name="reason",
            field=models.CharField(
                help_text="如：每日打卡、连续打卡奖励等", max_length=100, verbose_name="获得原因"
            ),
        ),
        migrations.AlterField(
            model_name="pointrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checkin",
            unique_together={("user", "activity", "created_at")},
        ),
    ]
