# Generated by Django 4.2.7 on 2026-03-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "checkins",
            "0004_pointrecord_related_checkin_alter_checkin_activity_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkin",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="accuracy",
            field=models.FloatField(
                blank=True, default=9999, null=True, verbose_name="精度(米)"
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                default=0,
                max_digits=10,
                verbose_name="纬度",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="location_name",
            field=models.CharField(
                blank=True, default="未获取位置", max_length=200, verbose_name="位置名称"
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                default=0,
                max_digits=10,
                verbose_name="经度",
            ),
        ),
    ]
