# Generated by Django 4.2.7 on 2026-03-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkins", "0006_checkin_check_in_date_and_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                    ("revoked", "已撤销"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
