# Generated by Django 4.2.7 on 2026-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
    ]
