# Generated by Django 4.2.7 on 2026-03-27 13:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="学号",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(default="", max_length=50, verbose_name="真实姓名"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女"), ("secret", "保密")],
                        default="secret",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^1[3-9]\\d{9}$", "请输入有效的手机号"
                            )
                        ],
                        verbose_name="手机号",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="院系"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="年级"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("teacher", "活动管理员"),
                            ("admin", "平台管理员"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否认证"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default.png",
                        upload_to="avatars/%Y/%m/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=500, verbose_name="个人简介"),
                ),
                ("points", models.PositiveIntegerField(default=0, verbose_name="当前积分")),
                (
                    "total_checkins",
                    models.PositiveIntegerField(default=0, verbose_name="累计打卡次数"),
                ),
                (
                    "streak_days",
                    models.PositiveIntegerField(default=0, verbose_name="当前连续打卡天数"),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(default=0, verbose_name="最长连续打卡天数"),
                ),
                (
                    "last_checkin_date",
                    models.DateField(blank=True, null=True, verbose_name="最后打卡日期"),
                ),
                (
                    "activities_joined",
                    models.PositiveIntegerField(default=0, verbose_name="参与活动数"),
                ),
                (
                    "activities_created",
                    models.PositiveIntegerField(default=0, verbose_name="创建活动数"),
                ),
                ("level", models.PositiveIntegerField(default=1, verbose_name="当前等级")),
                (
                    "level_title",
                    models.CharField(default="新手", max_length=20, verbose_name="等级称号"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "notify_activity",
                    models.BooleanField(default=True, verbose_name="活动提醒"),
                ),
                (
                    "notify_checkin",
                    models.BooleanField(default=True, verbose_name="打卡提醒"),
                ),
                (
                    "notify_system",
                    models.BooleanField(default=True, verbose_name="系统公告"),
                ),
                (
                    "public_profile",
                    models.BooleanField(default=True, verbose_name="公开个人资料"),
                ),
                (
                    "show_checkin",
                    models.BooleanField(default=True, verbose_name="显示打卡记录"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notification",
                    models.BooleanField(default=True, verbose_name="邮件通知"),
                ),
                (
                    "push_notification",
                    models.BooleanField(default=True, verbose_name="推送通知"),
                ),
                ("show_email", models.BooleanField(default=False, verbose_name="公开邮箱")),
                ("show_phone", models.BooleanField(default=False, verbose_name="公开手机")),
                ("dark_mode", models.BooleanField(default=False, verbose_name="深色模式")),
                (
                    "language",
                    models.CharField(default="zh-CN", max_length=10, verbose_name="语言"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_detail",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户设置",
                "verbose_name_plural": "用户设置",
            },
        ),
        migrations.CreateModel(
            name="PointHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="积分变动")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("earn", "获得"), ("spend", "消费"), ("deduct", "扣除")],
                        default="earn",
                        max_length=10,
                        verbose_name="交易类型",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分记录",
                "verbose_name_plural": "积分记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FollowRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_relations_as_follower",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关注者",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_relations_as_following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被关注者",
                    ),
                ),
            ],
            options={
                "verbose_name": "关注关系",
                "verbose_name_plural": "关注关系",
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="following",
                through="users.FollowRelation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("first_checkin", "首次打卡"),
                            ("streak_3", "连续3天"),
                            ("streak_7", "连续7天"),
                            ("streak_30", "连续30天"),
                            ("streak_100", "连续100天"),
                            ("points_100", "积分破百"),
                            ("points_500", "积分破五百"),
                            ("points_1000", "积分破千"),
                            ("creator", "活动创建者"),
                            ("popular", "人气王"),
                            ("social", "社交达人"),
                        ],
                        max_length=20,
                        verbose_name="成就类型",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="成就名称")),
                ("description", models.TextField(blank=True, verbose_name="成就描述")),
                (
                    "icon",
                    models.CharField(default="🏅", max_length=50, verbose_name="图标"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("bronze", "铜"),
                            ("silver", "银"),
                            ("gold", "金"),
                            ("platinum", "白金"),
                            ("diamond", "钻石"),
                        ],
                        default="bronze",
                        max_length=10,
                        verbose_name="等级",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获得时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户成就",
                "verbose_name_plural": "用户成就",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "achievement_type")},
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["student_id"], name="users_user_student_ffeaca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["department"], name="users_user_departm_52fe15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["points"], name="users_user_points_d9dafa_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["streak_days"], name="users_user_streak__23f5bc_idx"
            ),
        ),
    ]
