# Generated by Django 4.2.7 on 2026-03-01 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="积分变动")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("earn", "获得"), ("spend", "消费"), ("deduct", "扣除")],
                        default="earn",
                        max_length=10,
                        verbose_name="交易类型",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "积分记录",
                "verbose_name_plural": "积分记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notification",
                    models.BooleanField(default=True, verbose_name="邮件通知"),
                ),
                (
                    "push_notification",
                    models.BooleanField(default=True, verbose_name="推送通知"),
                ),
                ("show_email", models.BooleanField(default=False, verbose_name="公开邮箱")),
                ("show_phone", models.BooleanField(default=False, verbose_name="公开手机")),
                ("dark_mode", models.BooleanField(default=False, verbose_name="深色模式")),
                (
                    "language",
                    models.CharField(default="zh-CN", max_length=10, verbose_name="语言"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户设置",
                "verbose_name_plural": "用户设置",
            },
        ),
        migrations.AlterModelOptions(
            name="followrelation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "关注关系",
                "verbose_name_plural": "关注关系",
            },
        ),
        migrations.AlterModelOptions(
            name="userachievement",
            options={
                "ordering": ["-earned_at"],
                "verbose_name": "用户成就",
                "verbose_name_plural": "用户成就",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="activities_created",
            field=models.PositiveIntegerField(default=0, verbose_name="创建活动数"),
        ),
        migrations.AddField(
            model_name="user",
            name="activities_joined",
            field=models.PositiveIntegerField(default=0, verbose_name="参与活动数"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_checkin_date",
            field=models.DateField(blank=True, null=True, verbose_name="最后打卡日期"),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.PositiveIntegerField(default=1, verbose_name="当前等级"),
        ),
        migrations.AddField(
            model_name="user",
            name="level_title",
            field=models.CharField(default="新手", max_length=20, verbose_name="等级称号"),
        ),
        migrations.AddField(
            model_name="user",
            name="longest_streak",
            field=models.PositiveIntegerField(default=0, verbose_name="最长连续打卡天数"),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_activity",
            field=models.BooleanField(default=True, verbose_name="活动提醒"),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_checkin",
            field=models.BooleanField(default=True, verbose_name="打卡提醒"),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_system",
            field=models.BooleanField(default=True, verbose_name="系统公告"),
        ),
        migrations.AddField(
            model_name="user",
            name="public_profile",
            field=models.BooleanField(default=True, verbose_name="公开个人资料"),
        ),
        migrations.AddField(
            model_name="user",
            name="show_checkin",
            field=models.BooleanField(default=True, verbose_name="显示打卡记录"),
        ),
        migrations.AddField(
            model_name="user",
            name="streak_days",
            field=models.PositiveIntegerField(default=0, verbose_name="当前连续打卡天数"),
        ),
        migrations.AlterField(
            model_name="followrelation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
        ),
        migrations.AlterField(
            model_name="followrelation",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_relations_as_follower",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关注者",
            ),
        ),
        migrations.AlterField(
            model_name="followrelation",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_relations_as_following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被关注者",
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="achievement_type",
            field=models.CharField(
                choices=[
                    ("first_checkin", "首次打卡"),
                    ("streak_3", "连续3天"),
                    ("streak_7", "连续7天"),
                    ("streak_30", "连续30天"),
                    ("streak_100", "连续100天"),
                    ("points_100", "积分破百"),
                    ("points_500", "积分破五百"),
                    ("points_1000", "积分破千"),
                    ("creator", "活动创建者"),
                    ("popular", "人气王"),
                    ("social", "社交达人"),
                ],
                max_length=20,
                verbose_name="成就类型",
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="description",
            field=models.TextField(blank=True, verbose_name="成就描述"),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="icon",
            field=models.CharField(default="🏅", max_length=50, verbose_name="图标"),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="level",
            field=models.CharField(
                choices=[
                    ("bronze", "铜"),
                    ("silver", "银"),
                    ("gold", "金"),
                    ("platinum", "白金"),
                    ("diamond", "钻石"),
                ],
                default="bronze",
                max_length=10,
                verbose_name="等级",
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["points"], name="users_user_points_d9dafa_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["streak_days"], name="users_user_streak__23f5bc_idx"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings_detail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="pointhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
