# Generated by Django 4.2.7 on 2026-03-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="打卡备注")),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=200, verbose_name="位置名称"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="纬度"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="经度"
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(blank=True, null=True, verbose_name="精度(米)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "points_earned",
                    models.PositiveIntegerField(default=0, verbose_name="获得积分"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="打卡时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="activities.activity",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin",
                        to="activities.activityregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "打卡记录",
                "verbose_name_plural": "打卡记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckInPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="checkins/%Y/%m/%d/", verbose_name="照片"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="checkins.checkin",
                    ),
                ),
            ],
            options={
                "verbose_name": "打卡照片",
                "verbose_name_plural": "打卡照片",
            },
        ),
    ]
