# Generated by Django 4.2.7 on 2026-03-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="活动标题")),
                ("description", models.TextField(verbose_name="活动描述")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activities/covers/%Y/%m/",
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="关闭时间"),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "registration_deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="报名截止时间"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="活动地点")),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(default=50, verbose_name="最大参与人数"),
                ),
                (
                    "min_participants",
                    models.PositiveIntegerField(default=1, verbose_name="最小参与人数"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=10, verbose_name="积分奖励"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("upcoming", "即将开始"),
                            ("ongoing", "进行中"),
                            ("ended", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("requirements", models.TextField(blank=True, verbose_name="参与要求")),
                (
                    "allow_checkin_before_start",
                    models.BooleanField(default=False, verbose_name="允许开始前打卡"),
                ),
                (
                    "checkin_radius",
                    models.PositiveIntegerField(default=500, verbose_name="打卡范围(米)"),
                ),
                (
                    "checkin_review_mode",
                    models.CharField(
                        choices=[
                            ("auto", "自动通过"),
                            ("manual", "人工审核"),
                            ("risk", "异常审核"),
                        ],
                        default="auto",
                        max_length=10,
                        verbose_name="打卡审核模式",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "活动",
                "verbose_name_plural": "活动",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="拟申请活动标题")),
                ("description", models.TextField(verbose_name="活动说明")),
                ("apply_reason", models.TextField(blank=True, verbose_name="申请理由")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activities/applications/%Y/%m/",
                        verbose_name="封面图片",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="计划开始时间")),
                ("end_time", models.DateTimeField(verbose_name="计划结束时间")),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="计划报名截止时间"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="计划地点")),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(default=50, verbose_name="最大参与人数"),
                ),
                (
                    "min_participants",
                    models.PositiveIntegerField(default=1, verbose_name="最小参与人数"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=10, verbose_name="积分奖励"),
                ),
                ("requirements", models.TextField(blank=True, verbose_name="参与要求")),
                (
                    "checkin_radius",
                    models.PositiveIntegerField(default=500, verbose_name="打卡范围(米)"),
                ),
                (
                    "checkin_review_mode",
                    models.CharField(
                        choices=[
                            ("auto", "自动通过"),
                            ("manual", "人工审核"),
                            ("risk", "异常审核"),
                        ],
                        default="auto",
                        max_length=10,
                        verbose_name="打卡审核模式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="审核意见")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "活动申请",
                "verbose_name_plural": "活动申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "活动评论",
                "verbose_name_plural": "活动评论",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="分类名称"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-tag", max_length=50, verbose_name="图标类名"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=20, verbose_name="颜色"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "活动分类",
                "verbose_name_plural": "活动分类",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ActivityRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "已报名"),
                            ("checked_in", "已打卡"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="报名时间"),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="打卡时间"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="activities.activity",
                        verbose_name="活动",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动报名",
                "verbose_name_plural": "活动报名",
            },
        ),
    ]
