# Generated by Django 4.2.7 on 2026-03-27 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activityregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_registrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="activities.activity",
                verbose_name="所属活动",
            ),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="activities.activitycomment",
                verbose_name="父评论",
            ),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评论用户",
            ),
        ),
        migrations.AddField(
            model_name="activityapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="申请人",
            ),
        ),
        migrations.AddField(
            model_name="activityapplication",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activities.category",
                verbose_name="分类",
            ),
        ),
        migrations.AddField(
            model_name="activityapplication",
            name="created_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_applications",
                to="activities.activity",
                verbose_name="生成的活动",
            ),
        ),
        migrations.AddField(
            model_name="activityapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_activity_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activities.category",
                verbose_name="分类",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关闭操作人",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="活动管理者",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityregistration",
            unique_together={("user", "activity")},
        ),
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(
                fields=["activity"], name="activities__activit_3b29a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(fields=["user"], name="activities__user_id_8c6b83_idx"),
        ),
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(
                fields=["parent"], name="activities__parent__cd3add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["status", "start_time"], name="activities__status_2c8935_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["category"], name="activities__categor_f36a4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["creator"], name="activities__creator_158a3b_idx"
            ),
        ),
    ]
