# Generated by Django 4.2.7 on 2026-03-02 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_category_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "活动分类",
                "verbose_name_plural": "活动分类",
            },
        ),
    ]
