# Generated by Django 4.2.7 on 2026-03-18 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0004_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitycomment",
            name="likes",
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否显示"),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="activitycomment",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="activities.activity",
                verbose_name="所属活动",
            ),
        ),
        migrations.AlterField(
            model_name="activitycomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
        ),
        migrations.AlterField(
            model_name="activitycomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="activities.activitycomment",
                verbose_name="父评论",
            ),
        ),
        migrations.AlterField(
            model_name="activitycomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评论用户",
            ),
        ),
        migrations.AlterField(
            model_name="activityregistration",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="activities.activity",
                verbose_name="活动",
            ),
        ),
        migrations.AlterField(
            model_name="activityregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_registrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(
                fields=["activity"], name="activities__activit_3b29a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(fields=["user"], name="activities__user_id_8c6b83_idx"),
        ),
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(
                fields=["parent"], name="activities__parent__cd3add_idx"
            ),
        ),
    ]
