# Generated by Django 4.2.7 on 2026-03-19 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0005_remove_activitycomment_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="关闭时间"),
        ),
        migrations.AddField(
            model_name="activity",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关闭操作人",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="活动管理者",
            ),
        ),
    ]
