# Generated by Django 4.2.7 on 2026-03-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0006_activity_closed_at_activity_closed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="activities/covers/%Y/%m/",
                verbose_name="封面图片",
            ),
        ),
    ]
