# Generated by Django 4.2.7 on 2026-03-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0007_alter_activity_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="checkin_review_mode",
            field=models.CharField(
                choices=[("auto", "自动通过"), ("manual", "人工审核"), ("risk", "异常审核")],
                default="auto",
                help_text="auto=自动通过，manual=人工审核，risk=异常审核",
                max_length=10,
                verbose_name="打卡审核模式",
            ),
        ),
    ]
